---
- hosts: workstation

  tasks:
    - name: install apps from homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - ack
        - bazaar
        - git
        - gnu-getopt
        - gpg
        - gpg-agent
        - go
        - htop-osx
        - mercurial
        - python
        - tmux
        - wget
        # For password-manager
        - tree
        - pwgen
        - libgfshare
        - encfs
        - osxfuse

    - name: fix pbcopy inside tmux
      homebrew: name=reattach-to-user-namespace install_options=wrap-pbcopy-and-pbpaste state=present

    - name: install pip
      shell: which pip > /dev/null || curl -LSs https://bootstrap.pypa.io/get-pip.py | python
      sudo: yes

    - name: install apps from pip
      pip: name={{ item }}
      sudo: yes
      with_items:
        - virtualenv
        - virtualenvwrapper
