---
- hosts: workstation

  tasks:
    - name: print from playbook
      debug: msg="in vim.yml"

    - name: create bundle and autoload
      file: path=~/.vim/{{ item }} recurse=yes state=directory
      with_items:
        - bundle
        - autoload

    - name: install pathogen
      command: curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim creates=~/.vim/autoload/pathogen.vim

    - name: install NerdTree
      git: repo=https://github.com/scrooloose/nerdtree.git dest=~/vim/bundles/nerdtree

    - name: install vim-puppet
      git: repo=https://github.com/rodjek/vim-puppet.git dest=~/vim/bundles/vim-puppet
