---
sources:
  git:
    - name: 'osx'
      repo: 'https://github.com/spencergibb/ansible-osx'
      playbooks:
        - homebrew.yml
        - vagrant.yml
        - dropbox.yml
        - chrome-beta.yml
        - iterm2.yml

    - name: 'bootstrap'
      repo: 'git@github.com:robyoung/ansible-bootstrap.git'
      playbooks:
        - projects.yml
        - vim.yml
        - virtualbox.yml
        - dotfiles.yml
        - zsh.yml
        - apps.yml
